export const translations = {
  es: {
    inicio: "Inicio",
    series: "Series",
    peliculas: "Películas",
    novedades: "Novedades",
    explorar: "Explorar por idiomas",
    suscribete: "Suscríbete",
    idioma: "Español",
    idiomacat: "Catalán",
    estreno: "ESTRENO RESTFLIX",
    reproducir: "Reproducir",
    info: "Más información",
    terror: "Esta noche está vigilante en las ventanas.",
    thriller: "Thrillers que te pondrán los pelos de punta.",
    comedia: "¡El resbalón con el que te vas a descojonar!",
    ver: "VER MÁS",
    privacidad: "Política de privacidad",
    preferencias: "Gestionar preferencias",
    uso: "Condiciones de uso",
    ayuda: "Centro de ayuda",
    team: "RESTflix.com es un proyecto de Ana Mari F. Emii S. Jonathan G. y Sandra R."
  },
  de: {
    inicio: "Zu Hause",
    series: "Fernsehserie",
    peliculas: "Filme",
    novedades: "Nachricht",
    explorar: "Nach Sprachen erkunden",
    suscribete: "Abonnieren",
    idioma: "Spanisch",
    idiomacat: "Deutsch",
    estreno: "Premiere Restflix",
    reproducir: "Spielen",
    info: "Mehr Informationen",
    terror: "Heute Abend schaut er am Fenster zu.",
    thriller: "Thriller, die einem die Haare zu Berge stehen lassen.",
    comedia: "Der Slip, der Sie verrückt machen wird!",
    ver: "MEHR SEHEN",
    privacidad: "Datenschutzrichtliniea",
    preferencias: "Einstellungen verwalten",
    uso: "Nutzungsbedingungen",
    ayuda: "Hilfezentrum",
    team: "RESTFlix ist ein projekt von Ana Mari F. Emii S. Jonathan G. und Sandra R."
  },
};
